# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240708_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paiement',
            field=models.CharField(default='AWAIT', max_length=8),
        ),
    ]
