# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-07 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=20)),
                ('chapter_created_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, unique=True)),
                ('course_created_date', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('for_everybody', models.BooleanField(default=True)),
                ('niveau', models.CharField(default='', max_length=8)),
                ('students', models.ManyToManyField(related_name='students_to_course', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to=b'')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text_block_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to=b'')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('yt_link_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
