# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20240708_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note_choix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='note_question',
            field=models.IntegerField(default=0),
        ),
    ]
