# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choix', '0002_auto_20240712_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.Course'),
        ),
    ]
